import Foundation
import MCP
import SwiftMageXKit

/// Per-tool `CallTool` dispatch: typed argument parsing → orchestrator call →
/// `CallTool.Result` (success or `isError: true`).
///
/// Schema-level problems (missing required keys, wrong types) propagate as
/// `MCPError.invalidParams` so the SDK can return a proper JSON-RPC error.
/// Kit-level failures (`SwiftMageXError`) are mapped to a content-bearing
/// result with `isError: true`, preserving the spec §13 error category so the
/// calling agent can react to it (spec §7).
enum ToolHandlers {
    // MARK: - generate_image

    static func generate(
        arguments: [String: Value]?,
        provider: any ImageProvider
    ) async throws -> CallTool.Result {
        let input = try GenerateImageTool.parse(arguments)

        do {
            let request = GenerationRequest(
                prompt: input.prompt,
                size: input.size,
                count: input.count,
                seed: input.seed,
                model: input.model
            )
            let written = try await SwiftMageXOrchestrator.generate(
                request: request,
                output: input.output,
                provider: provider
            )
            var content: [Tool.Content] = [
                .text(text: summaryText(for: written, provider: provider.id), annotations: nil, _meta: nil)
            ]
            // Spec §7: include the generated bytes as MCP image content so the
            // calling model can inspect what was produced.
            for image in written {
                if let data = try? Data(contentsOf: image.path) {
                    content.append(.image(
                        data: data.base64EncodedString(),
                        mimeType: image.format.mimeType,
                        annotations: nil,
                        _meta: nil
                    ))
                }
            }
            return CallTool.Result(content: content, isError: false)
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - edit_image

    static func edit(
        arguments: [String: Value]?,
        provider: any ImageProvider
    ) async throws -> CallTool.Result {
        let input = try EditImageTool.parse(arguments)

        do {
            let request = GenerationRequest(
                prompt: input.prompt,
                size: .square,
                count: input.count,
                seed: input.seed,
                model: input.model
            )
            let written = try await SwiftMageXOrchestrator.edit(
                input: input.image,
                references: input.references,
                mask: input.mask,
                request: request,
                output: input.output,
                provider: provider
            )
            var content: [Tool.Content] = [
                .text(text: summaryText(for: written, provider: provider.id), annotations: nil, _meta: nil)
            ]
            // Spec §7: include the edited bytes as MCP image content so the
            // calling model can inspect what was produced.
            for image in written {
                if let data = try? Data(contentsOf: image.path) {
                    content.append(.image(
                        data: data.base64EncodedString(),
                        mimeType: image.format.mimeType,
                        annotations: nil,
                        _meta: nil
                    ))
                }
            }
            return CallTool.Result(content: content, isError: false)
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - resize_image

    static func resize(arguments: [String: Value]?) throws -> CallTool.Result {
        let input = try ResizeImageTool.parse(arguments)

        do {
            let spec = ResizeSpec(width: input.width, height: input.height, fit: input.fit)
            let written = try SwiftMageXOrchestrator.resize(
                input: input.input,
                spec: spec,
                output: input.output,
                format: input.format,
                quality: input.quality
            )
            return CallTool.Result(
                content: [.text(text: summaryText(for: [written]), annotations: nil, _meta: nil)],
                isError: false
            )
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - overlay_text

    static func overlayText(arguments: [String: Value]?) throws -> CallTool.Result {
        let input = try OverlayTextTool.parse(arguments)

        do {
            let spec = TextSpec(
                text: input.text,
                position: input.position,
                fontName: input.font,
                fontSize: input.fontSize,
                color: input.color,
                strokeColor: input.stroke,
                strokeWidth: input.strokeWidth
            )
            let written = try SwiftMageXOrchestrator.overlayText(
                input: input.input,
                spec: spec,
                output: input.output
            )
            return CallTool.Result(
                content: [.text(text: summaryText(for: [written]), annotations: nil, _meta: nil)],
                isError: false
            )
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - composite_images

    static func composite(arguments: [String: Value]?) throws -> CallTool.Result {
        let input = try CompositeImagesTool.parse(arguments)

        do {
            let spec = CompositeSpec(
                position: input.position,
                scale: input.scale,
                offsetX: input.offsetX,
                offsetY: input.offsetY,
                opacity: input.opacity
            )
            let written = try SwiftMageXOrchestrator.composite(
                input: input.input,
                overlay: input.overlay,
                spec: spec,
                output: input.output,
                format: input.format,
                quality: input.quality
            )
            return CallTool.Result(
                content: [.text(text: summaryText(for: [written]), annotations: nil, _meta: nil)],
                isError: false
            )
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - appstore_screenshots

    static func appStore(arguments: [String: Value]?) throws -> CallTool.Result {
        let input = try AppStoreScreenshotsTool.parse(arguments)

        do {
            let written = try SwiftMageXOrchestrator.prepareAppStoreScreenshots(
                screenshot: input.screenshot,
                background: input.background,
                frame: input.frame,
                frameSpec: input.frameSpec,
                caption: input.caption,
                devices: input.devices,
                placement: input.placement,
                orientation: input.orientation,
                output: input.output
            )
            return CallTool.Result(
                content: [.text(text: summaryText(for: written), annotations: nil, _meta: nil)],
                isError: false
            )
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - list_frames

    static func listFrames() -> CallTool.Result {
        let frames = DeviceFrameCatalog.all
        if frames.isEmpty {
            return CallTool.Result(
                content: [.text(text: "(no bundled frames)", annotations: nil, _meta: nil)],
                isError: false
            )
        }
        var lines = ["OK"]
        for frame in frames {
            var parts = ["\(frame.id) → \(frame.deviceID): \(frame.label)"]
            if let license = frame.license {
                parts.append("(\(license))")
            }
            lines.append(parts.joined(separator: " "))
        }
        return CallTool.Result(
            content: [.text(text: lines.joined(separator: "\n"), annotations: nil, _meta: nil)],
            isError: false
        )
    }

    // MARK: - remove_background

    static func removeBackground(arguments: [String: Value]?) throws -> CallTool.Result {
        let input = try RemoveBackgroundTool.parse(arguments)

        do {
            let written = try SwiftMageXOrchestrator.removeBackground(
                input: input.input,
                output: input.output
            )
            return CallTool.Result(
                content: [.text(text: summaryText(for: [written]), annotations: nil, _meta: nil)],
                isError: false
            )
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - smart_crop

    static func smartCrop(arguments: [String: Value]?) throws -> CallTool.Result {
        let input = try SmartCropTool.parse(arguments)

        do {
            let spec = SmartCropSpec(
                aspectWidth: input.aspectWidth,
                aspectHeight: input.aspectHeight
            )
            let written = try SwiftMageXOrchestrator.smartCrop(
                input: input.input,
                spec: spec,
                output: input.output,
                format: input.format,
                quality: input.quality
            )
            return CallTool.Result(
                content: [.text(text: summaryText(for: [written]), annotations: nil, _meta: nil)],
                isError: false
            )
        } catch let error as SwiftMageXError {
            return errorResult(error)
        }
    }

    // MARK: - Helpers

    /// Builds the human-readable summary that accompanies every tool result.
    /// The first line is `OK`; subsequent lines list each absolute path with
    /// its format and pixel dimensions — agents can parse this trivially, and
    /// humans can read it without re-decoding the file.
    private static func summaryText(
        for images: [WrittenImage],
        provider: String? = nil
    ) -> String {
        var lines = ["OK"]
        if let provider = provider {
            lines.append("provider: \(provider)")
        }
        for image in images {
            lines.append("\(image.path.path) (\(image.format.rawValue) \(image.width)x\(image.height))")
        }
        return lines.joined(separator: "\n")
    }

    /// Maps a ``SwiftMageXError`` into the `isError: true` result envelope.
    /// The category string is the same one the CLI reports in its JSON
    /// envelope (spec §13), so an agent can branch on it.
    private static func errorResult(_ error: SwiftMageXError) -> CallTool.Result {
        let text = "[\(error.category)] \(error.message)"
        return CallTool.Result(
            content: [.text(text: text, annotations: nil, _meta: nil)],
            isError: true
        )
    }
}
